<style>
    .message { margin: 5px 0 0 5px; border: 1px solid grey; width: 450px; min-height: 100px;}
    .author { margin-left: 10px; }
    .text { padding-left: 15px; padding-top: 15px; }
    .date {color: grey; font-size: 11px;}
    .admin a { color: #46468b; float: right; padding-right: 15px; }
</style>

Вы вошли как <?=$this->user->getName();?>

<form action="/user/logout">
    <input type="submit" value="Выйти">
</form>


Список сообщений: <br>
<?php
/** @var $message \App\Model\Message */
/** @var $user \App\Model\User */
$user = $this->user;
?>
<?php if($messages = $this->messages): ?>
    <?php foreach ($messages as $message): ?>
        <div class="message">
            <?php if($user->isAdmin()): ?>
            <div class="admin">
                <a href="/admin/deleteMessage/?id=<?=$message->getId();?>">Удалить</a>
                <a href="/api/getUserMessages/?user_id=<?=$message->getAuthorId();?>">Получить сообщения пользователя</a>
               
            </div>
            <?php endif; ?>
            <span class="date"><?=$message->getCreatedAt();?> </span>
            <?php if($author = $message->getAuthor()):?>
                <span class="author"><?=htmlspecialchars($author->getName());?></span>
            <?php else: ?>
                <span class="author">Сообщение от удаленного пользователя</span>
            <?php endif; ?>
            <div class="text"><?=htmlspecialchars(nl2br($message->getText()));?></div>
            <?php if($message->getImage()):?>
                <div><img src="/images/<?=$message->getImage();?>" style="width: 150px;"></div>
            <?php endif;?>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    Сообщений пока нет
<?php endif; ?>

Добавить сообщение
<form enctype="multipart/form-data" action="/blog/addMessage" method="POST">
    <textarea style="width: 250px; height: 150px;" type="text" value="" name="text"></textarea><br><br>
    Изображение: <input type="file" name="image"><br>
    <input type="submit" value="Отправить">
</form>